# Generated by Django 5.0.6 on 2024-07-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_year', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Experiences',
            },
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': 'UserInfo'},
        ),
    ]
